[package]
name = "gooir-file-tree-build"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
gooir-capability.workspace = true
gooir-derive.workspace = true
gooir-file-tree-materializer.workspace = true
gooir-file-tree-v1.workspace = true

[dev-dependencies]
gooir-package.workspace = true
gooir-planning.workspace = true
serde_json.workspace = true
sha2.workspace = true
tempfile.workspace = true

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all = "warn"
pedantic = "warn"
