use std::collections::BTreeMap;
use std::fs;
use std::os::unix::fs::PermissionsExt as _;
use std::path::{Path, PathBuf};
use std::process::{Command, Output};

use gooir_capability::authority::{
    AdmissionAuthorityId, AdmissionPolicy, ConformanceAttester, ConformanceAuthority,
    ObservationAuthority, ObservationSourceId, SourceObservation,
};
use gooir_capability::protocol::{
    ArtifactDigest, ConformanceSuiteId, EvidenceDigest, EvidenceKindId, EvidenceRef,
    ImplementationId,
};
use gooir_capability::{CapabilityId, CapabilitySpec, Fact, InputPort, OutputPort, PortName};
use gooir_derive::LocalAttesterBinding;
use gooir_file_tree_v1::{dialect_id, file_tree_value_kind};
use gooir_package::{
    ConformanceSuiteDeclaration, DialectDeclaration, ImplementationOfferDeclaration, PackageId,
    PackageManifest, PackageResource, ResourceDigest, ResourceName, ValueKindDeclaration,
    write_manifest,
};
use serde_json::json;
use sha2::{Digest as _, Sha256};

const VERSION: &str = "1.0.0";
const PROVIDER_ARTIFACT: &[u8] = br"#!/usr/bin/python3
import base64, hashlib, json, sys

def identity(document, field):
    value = dict(document)
    del value[field]
    canonical = json.dumps(value, ensure_ascii=False, separators=(',', ':'), sort_keys=True).encode()
    return 'sha256:' + hashlib.sha256(canonical).hexdigest()

def file(path, media_type, content):
    return {
        'path': path,
        'media_type': media_type,
        'content_digest': 'sha256:' + hashlib.sha256(content).hexdigest(),
        'content': base64.b64encode(content).decode()
    }

invocation = json.load(sys.stdin)
declaration = invocation['specification']['output_ports'][0]
tree = {'files': [
    file('README.md', 'text/markdown', b'generated by gooir\n'),
    file('src/data.bin', 'application/octet-stream', bytes([0, 159, 146, 150]))
]}
fact_body = {'value_kind': declaration['value_kind'], 'payload': tree}
fact = {'id': identity({'id': '', **fact_body}, 'id'), **fact_body}
result = {
    'result_id': '',
    'protocol': 'org.gooi.capability.result/v1',
    'invocation_id': invocation['invocation_id'],
    'outcome': {'status': 'produced', 'outputs': [{'port': declaration['name'], 'fact': fact}]},
    'evidence': []
}
result['result_id'] = identity(result, 'result_id')
json.dump(result, sys.stdout, ensure_ascii=False, separators=(',', ':'))
";

const ATTESTER_ARTIFACT: &[u8] = br"#!/usr/bin/python3
import hashlib, json, sys

def identity(document, field):
    value = dict(document)
    del value[field]
    canonical = json.dumps(value, ensure_ascii=False, separators=(',', ':'), sort_keys=True).encode()
    return 'sha256:' + hashlib.sha256(canonical).hexdigest()

request = json.load(sys.stdin)
assessment = {
    'assessment_id': '',
    'protocol': 'org.gooi.authority.conformance-assessment/v1',
    'invocation_id': request['invocation']['invocation_id'],
    'result_id': request['result']['result_id'],
    'candidate_id': request['candidate']['candidate_id'],
    'authority': request['authority'],
    'outcome': 'passed',
    'checks': {'exact-file-tree': {'outcome': 'passed', 'evidence': []}},
    'evidence': []
}
assessment['assessment_id'] = identity(assessment, 'assessment_id')
json.dump(assessment, sys.stdout, ensure_ascii=False, separators=(',', ':'))
";

struct Fixture {
    _root: tempfile::TempDir,
    package: PathBuf,
    policy: PathBuf,
    observation: PathBuf,
    attester: PathBuf,
}

impl Fixture {
    fn new(source_extensions: BTreeMap<String, serde_json::Value>) -> Self {
        let root = tempfile::tempdir().unwrap();
        let package = root.path().join("package");
        fs::create_dir(&package).unwrap();
        fs::write(package.join("provider"), PROVIDER_ARTIFACT).unwrap();
        fs::write(package.join("attester"), ATTESTER_ARTIFACT).unwrap();
        fs::write(
            package.join(gooir_package::PACKAGE_MANIFEST_FILE),
            write_manifest(&package_manifest()).unwrap(),
        )
        .unwrap();

        let source_fact = Fact::new(source_kind(), json!({"model": "example"})).unwrap();
        let source_authority = ObservationAuthority::new(
            ObservationSourceId::new("test.source", "fixture", VERSION),
            ImplementationId::new("test.observer", "memory", VERSION),
            ArtifactDigest::parse(sha('c')).unwrap(),
            source_fact.value_kind.clone(),
            evidence_kind(),
            source_extensions,
        )
        .unwrap();
        let observation = SourceObservation::new(
            source_fact,
            source_authority.clone(),
            EvidenceRef::new(
                evidence_kind(),
                EvidenceDigest::parse(sha('d')).unwrap(),
                "memory://cli-file-tree-build",
                BTreeMap::new(),
            )
            .unwrap(),
            Vec::new(),
            BTreeMap::new(),
        )
        .unwrap();
        let attester_authority = ConformanceAuthority::new(
            suite(),
            ConformanceAttester::new(
                attester_implementation(),
                ArtifactDigest::parse(raw_digest(ATTESTER_ARTIFACT)).unwrap(),
                BTreeMap::new(),
            )
            .unwrap(),
            BTreeMap::new(),
        )
        .unwrap();
        let policy = AdmissionPolicy::new(
            AdmissionAuthorityId::new("test.admission", "cli-build", VERSION),
            vec![attester_authority.clone()],
            vec![source_authority],
            BTreeMap::new(),
        )
        .unwrap();
        let binding = LocalAttesterBinding {
            authority: attester_authority,
            package: package_id(),
            resource: ResourceName::parse("attester").unwrap(),
        };

        let policy_path = root.path().join("policy.json");
        let observation_path = root.path().join("observation.json");
        let attester_path = root.path().join("attester.json");
        fs::write(&policy_path, serde_json::to_vec(&policy).unwrap()).unwrap();
        fs::write(&observation_path, serde_json::to_vec(&observation).unwrap()).unwrap();
        fs::write(&attester_path, serde_json::to_vec(&binding).unwrap()).unwrap();

        Self {
            _root: root,
            package,
            policy: policy_path,
            observation: observation_path,
            attester: attester_path,
        }
    }

    fn build(&self, destination: &Path, include_attester: bool) -> Output {
        let mut command = Command::new(env!("CARGO_BIN_EXE_gooir"));
        command
            .arg("build")
            .arg(destination)
            .arg("--package")
            .arg(&self.package)
            .arg("--policy")
            .arg(&self.policy)
            .arg("--observation")
            .arg(&self.observation);
        if include_attester {
            command.arg("--attester").arg(&self.attester);
        }
        command
            .args([
                "--stdin-bytes",
                "1048576",
                "--stdout-bytes",
                "1048576",
                "--stderr-bytes",
                "65536",
                "--timeout-ms",
                "5000",
                "--max-files",
                "16",
                "--max-directories",
                "16",
                "--max-file-bytes",
                "1048576",
                "--max-total-bytes",
                "4194304",
                "--directory-mode",
                "0750",
                "--file-mode",
                "0640",
            ])
            .output()
            .unwrap()
    }
}

#[test]
fn cli_build_executes_admits_and_publishes_a_physical_project() {
    let fixture = Fixture::new(BTreeMap::new());
    let output_parent = tempfile::tempdir().unwrap();
    let destination = output_parent.path().join("generated-project");

    let output = fixture.build(&destination, true);

    assert!(
        output.status.success(),
        "stdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    assert_eq!(
        fs::read(destination.join("README.md")).unwrap(),
        b"generated by gooir\n"
    );
    assert_eq!(
        fs::read(destination.join("src/data.bin")).unwrap(),
        vec![0, 159, 146, 150]
    );
    assert_eq!(
        fs::metadata(&destination).unwrap().permissions().mode() & 0o777,
        0o750
    );
    assert_eq!(
        fs::metadata(destination.join("README.md"))
            .unwrap()
            .permissions()
            .mode()
            & 0o777,
        0o640
    );
    let stdout = String::from_utf8(output.stdout).unwrap();
    assert!(stdout.contains("materialized admitted FileTree sha256:"));
    assert!(stdout.contains(&format!("destination {}", destination.display())));
    assert!(stdout.contains("README.md (19 byte(s), sha256:"));
    assert!(stdout.contains("durability "));
    assert!(
        stdout.contains("parent directory synced")
            || stdout.contains("uncertain; do not retry as if publication failed")
    );
    assert!(stdout.contains("modes directory 750, file 640"));

    let second = fixture.build(&destination, true);
    assert_eq!(second.status.code(), Some(1));
    let stderr = String::from_utf8(second.stderr).unwrap();
    assert!(stderr.contains("FileTree materialization failed"));
    assert!(stderr.contains("already exists"));
    assert!(stderr.contains("admitted fact sha256:"));
    assert_eq!(
        fs::read(destination.join("README.md")).unwrap(),
        b"generated by gooir\n"
    );
}

#[test]
fn blocked_cli_build_never_creates_the_destination() {
    let fixture = Fixture::new(BTreeMap::new());
    let output_parent = tempfile::tempdir().unwrap();
    let destination = output_parent.path().join("blocked-project");

    let output = fixture.build(&destination, false);

    assert_eq!(output.status.code(), Some(3));
    assert!(!destination.exists());
    let stdout = String::from_utf8(output.stdout).unwrap();
    assert!(stdout.contains("blocked plan sha256:"));
    assert!(stdout.contains("missing independent attester"));
    assert!(stdout.contains("supply the missing implementation or attester"));
}

#[test]
fn unknown_reachable_authority_semantics_fail_before_publication() {
    let fixture = Fixture::new(BTreeMap::from([(
        "org.example/source-semantics".to_owned(),
        json!(true),
    )]));
    let output_parent = tempfile::tempdir().unwrap();
    let destination = output_parent.path().join("refused-project");

    let output = fixture.build(&destination, true);

    assert_eq!(output.status.code(), Some(1));
    assert!(!destination.exists());
    let stderr = String::from_utf8(output.stderr).unwrap();
    assert!(stderr.contains("refused before materialization effects"));
    assert!(stderr.contains("observation authority"));
    assert!(stderr.contains("org.example/source-semantics"));
    assert!(stderr.contains("admitted fact sha256:"));
}

fn package_manifest() -> PackageManifest {
    let provider_resource = package_resource("provider", "provider", PROVIDER_ARTIFACT);
    let attester_resource = package_resource("attester", "attester", ATTESTER_ARTIFACT);
    let mut dialects = vec![
        DialectDeclaration {
            id: dialect_id(),
            value_kinds: vec![ValueKindDeclaration {
                id: file_tree_value_kind(),
                schema: None,
                extensions: BTreeMap::new(),
            }],
            extensions: BTreeMap::new(),
        },
        DialectDeclaration {
            id: source_kind().dialect(),
            value_kinds: vec![ValueKindDeclaration {
                id: source_kind(),
                schema: None,
                extensions: BTreeMap::new(),
            }],
            extensions: BTreeMap::new(),
        },
    ];
    dialects.sort_by(|left, right| left.id.cmp(&right.id));
    PackageManifest::new(
        package_id(),
        Vec::new(),
        vec![attester_resource, provider_resource],
        dialects,
        vec![ConformanceSuiteDeclaration {
            id: suite(),
            extensions: BTreeMap::new(),
        }],
        vec![CapabilitySpec {
            id: capability(),
            input_ports: vec![InputPort::complete(port("source"), source_kind())],
            output_ports: vec![OutputPort::new(port("tree"), file_tree_value_kind())],
            default_conformance_suite: suite().to_string(),
            extensions: BTreeMap::new(),
        }],
        vec![ImplementationOfferDeclaration {
            implementation: provider_implementation(),
            capability: capability(),
            artifact: ResourceName::parse("provider").unwrap(),
            extensions: BTreeMap::new(),
        }],
        BTreeMap::new(),
    )
    .unwrap()
}

fn package_resource(name: &str, path: &str, bytes: &[u8]) -> PackageResource {
    PackageResource {
        name: ResourceName::parse(name).unwrap(),
        path: path.to_owned(),
        media_type: "application/octet-stream".to_owned(),
        size: u64::try_from(bytes.len()).unwrap(),
        digest: ResourceDigest::parse(raw_digest(bytes)).unwrap(),
        extensions: BTreeMap::new(),
    }
}

fn package_id() -> PackageId {
    PackageId::parse("test.cli-file-tree-build@1.0.0").unwrap()
}

fn source_kind() -> gooir_capability::ValueKindId {
    gooir_capability::ValueKindId::new("test.source", "model", VERSION)
}

fn capability() -> CapabilityId {
    CapabilityId::new("test.capability", "build-file-tree", VERSION)
}

fn provider_implementation() -> ImplementationId {
    ImplementationId::new("test.provider", "file-tree", VERSION)
}

fn attester_implementation() -> ImplementationId {
    ImplementationId::new("test.attester", "file-tree", VERSION)
}

fn suite() -> ConformanceSuiteId {
    ConformanceSuiteId::new("test.conformance", "file-tree", VERSION)
}

fn evidence_kind() -> EvidenceKindId {
    EvidenceKindId::new("test.evidence", "source", VERSION)
}

fn port(name: &str) -> PortName {
    PortName::parse(name).unwrap()
}

fn sha(byte: char) -> String {
    format!("sha256:{}", byte.to_string().repeat(64))
}

fn raw_digest(bytes: &[u8]) -> String {
    let digest = Sha256::digest(bytes);
    format!("sha256:{digest:x}")
}
