#!/usr/bin/env python3
"""A GOOIR capability provider that happens not to be Rust.

It lowers the neutral data model to TypeScript declarations. What is worth
noticing is what is *not* here: no protocol check, no scan of the inputs, no
envelope unwrapping, no coverage decision, no response framing. That is the
`gooir` SDK's job, and it is the same job in every language.

What remains is the lowering, and the honest admission of what TypeScript
cannot carry.
"""
import os
import sys

# In the repository the SDK sits beside the example. A real plugin would depend
# on a published `gooir` package and pin its version; either way the manifest
# lists the SDK among the files the host measures, because it is part of what
# runs.
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "../../../sdk/python"))

import gooir  # noqa: E402

MODEL = "org.gooi.semantics.data_model/model@1.0.0"
TYPES = "org.gooi.artifact.typescript/model_types@0.1.0"
DEFEATERS = "org.gooi.plugin.typescript_types/defeaters@0.1.0"

# The waist's domains, in TypeScript's terms. A domain with no faithful TS
# representation is reported as a loss rather than quietly widened.
SCALARS = {
    "text": "string",
    "uuid": "string",
    "integer": "number",
    "big_integer": "bigint",
    "float": "number",
    "boolean": "boolean",
    "timestamp": "string",
    "date": "string",
    "time": "string",
    "json": "unknown",
    "bytes": "string",
    "decimal": "string",
}

# Domains TypeScript has no type for, only a representation of.
NARROWED = {
    "timestamp": "carried as an ISO string",
    "date": "carried as an ISO string",
    "time": "carried as an ISO string",
    "decimal": "carried as a string to preserve precision",
}


def field_type(ctx, field):
    enumeration = field.get("enumeration")
    if enumeration and enumeration.get("members"):
        return " | ".join('"{}"'.format(m) for m in enumeration["members"])

    ty = field.get("ty")
    scalar = ty.get("scalar") if isinstance(ty, dict) else None

    if scalar == "enumeration":
        ctx.defeat("looked_and_blocked", field["name"], "the enumeration carried no members")
        return "string"
    if scalar in SCALARS:
        if scalar in NARROWED:
            ctx.defeat("authority_cannot_express", field["name"], "{} is {}".format(scalar, NARROWED[scalar]))
        return SCALARS[scalar]

    ctx.defeat("authority_cannot_express", field["name"], "no TypeScript domain for {}".format(scalar or ty))
    return "unknown"


def lower(ctx):
    model = ctx.input(MODEL)
    entities = (model or {}).get("entities") or []
    if not entities:
        raise gooir.ProviderError("the data model declares no entities")

    lines = ["// generated by org.gooi.plugin.typescript_types/provider.py"]
    for entity in sorted(entities, key=lambda e: e["name"]):
        lines.append("")
        lines.append("export interface {} {{".format(entity["name"]))
        for field in sorted(entity.get("fields") or [], key=lambda f: f["name"]):
            rendered = field_type(ctx, field)
            if field.get("list"):
                rendered = "Array<{}>".format(rendered)
            optional = field.get("nullable") != "required"
            if optional:
                rendered = "{} | null".format(rendered)
            lines.append("  {}{}: {};".format(field["name"], "?" if optional else "", rendered))
        lines.append("}")
    lines.append("")

    ctx.produce(TYPES, "\n".join(lines))


if __name__ == "__main__":
    gooir.run(lower, defeater_set=DEFEATERS)
