#!/usr/bin/env python3
"""A GOOIR capability provider that happens not to be Rust.

Reads one org.gooi.plugin/v1 request on stdin and writes one response on
stdout. It lowers the neutral data model to TypeScript declarations.

The point of this file is that nothing about it is special: it is a program
that reads JSON and writes JSON, and the registry validates its outputs the
same way it validates an in-process provider's.
"""
import json
import sys

PROTOCOL = "org.gooi.plugin/v1"

# The waist's domains, in TypeScript's terms. A domain with no faithful TS
# representation is reported as a loss rather than quietly widened.
SCALARS = {
    "text": "string",
    "uuid": "string",
    "integer": "number",
    "big_integer": "bigint",
    "float": "number",
    "boolean": "boolean",
    "timestamp": "string",
    "date": "string",
    "time": "string",
    "json": "unknown",
    "bytes": "string",
    "decimal": "string",
}


def fail(message):
    json.dump({"protocol": PROTOCOL, "error": message}, sys.stdout)
    sys.exit(0)


def field_type(field, losses):
    enumeration = field.get("enumeration")
    if enumeration and enumeration.get("members"):
        return " | ".join(json.dumps(m) for m in enumeration["members"])
    ty = field.get("ty")
    if isinstance(ty, dict) and "scalar" in ty:
        scalar = ty["scalar"]
        if scalar == "enumeration":
            losses.append(
                {"subject": field["name"], "detail": "enumeration carried no members"}
            )
            return "string"
        if scalar in SCALARS:
            if scalar in ("timestamp", "date", "time"):
                losses.append(
                    {
                        "subject": field["name"],
                        "detail": f"{scalar} is carried as an ISO string",
                    }
                )
            if scalar == "decimal":
                losses.append(
                    {
                        "subject": field["name"],
                        "detail": "decimal is a string to preserve precision",
                    }
                )
            return SCALARS[scalar]
    losses.append({"subject": field["name"], "detail": "no TypeScript domain"})
    return "unknown"


def main():
    try:
        request = json.load(sys.stdin)
    except Exception as error:  # noqa: BLE001 - reported over the wire
        fail(f"request was not valid JSON: {error}")

    if request.get("protocol") != PROTOCOL:
        fail(f"unexpected protocol {request.get('protocol')!r}")

    inputs = request.get("inputs") or []
    model = next(
        (
            i
            for i in inputs
            if i.get("fact_type", {}).get("package") == "org.gooi.semantics.data_model"
        ),
        None,
    )
    if model is None:
        fail("no data-model fact among the inputs")

    payload = model.get("payload") or {}
    entities = (payload.get("value") or {}).get("entities") or []
    if not entities:
        fail("the data model declares no entities")

    losses = []
    lines = ["// generated by org.gooi.plugin.typescript_types/provider.py"]
    for entity in sorted(entities, key=lambda e: e["name"]):
        lines.append("")
        lines.append(f"export interface {entity['name']} {{")
        for field in sorted(entity.get("fields") or [], key=lambda f: f["name"]):
            rendered = field_type(field, losses)
            if field.get("list"):
                rendered = f"Array<{rendered}>"
            optional = field.get("nullable") != "required"
            if optional:
                rendered = f"{rendered} | null"
            suffix = "?" if optional else ""
            lines.append(f"  {field['name']}{suffix}: {rendered};")
        lines.append("}")
    lines.append("")

    outputs = [
        {
            "fact_type": {
                "package": "org.gooi.artifact.typescript",
                "name": "model_types",
                "version": "0.1.0",
            },
            # Coverage is honest: any loss makes this partial.
            "coverage": "complete" if not losses else "partial",
            "payload": {"source": "\n".join(lines), "lossy": losses},
        }
    ]
    json.dump({"protocol": PROTOCOL, "outputs": outputs}, sys.stdout)


if __name__ == "__main__":
    main()
