[package]
name = "gooir-datamodel-pack"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
entity-spec = { workspace = true }
gooir-capability = { workspace = true }
gooir-provider = { workspace = true }
lift-defeasible = { workspace = true }
openapi-lowering = { workspace = true }
semantics-data-model-v1 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sql-ddl-lowering = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
