[package]
name = "buzz-cli-lifter"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
buzz-protocol-lifter.workspace = true
proc-macro2.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
syn.workspace = true
