[package]
name = "gooir-module-observer"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
gooir-capability.workspace = true
gooir-module-planning.workspace = true
gooir-module-v0.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_json_canonicalizer.workspace = true

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all = "warn"
pedantic = "warn"
