[package]
name = "gooir-artifact-sdk"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
base64.workspace = true
getrandom.workspace = true
gooir-capability.workspace = true
gooir-package.workspace = true
rustix.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_json_canonicalizer.workspace = true
sha2.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all = "warn"
pedantic = "warn"
