[package]
name = "gooir-file-tree-materializer"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
getrandom.workspace = true
gooir-capability.workspace = true
gooir-file-tree-v1.workspace = true
rustix.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all = "warn"
pedantic = "warn"
