[package]
name = "data-model-convergence"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
lift-defeasible = { workspace = true }
postgres-catalog-lifter = { workspace = true }
prisma-schema-lifter = { workspace = true }
semantics-data-model-v1 = { workspace = true }

[dev-dependencies]
lift-defeasible = { workspace = true }
