//! Lowers the neutral data-model waist into Prisma schema text.
//!
//! Lowering is the cheap, decidable direction: the mapping is authored here and
//! failure is a hard error rather than an inference. What the waist cannot
//! supply is reported as [`Lossy`] rather than invented, because a lowering that
//! silently fills gaps is how a middle stops being checkable.

use std::collections::BTreeMap;
use std::fmt::Write as _;

use lift_defeasible::{Defeasible, Defeat, DefeatKind};
use semantics_data_model_v1::{
    DataModel, DefaultOrigin, EntityShape, FieldShape, FieldType, Presence, ScalarType,
};

/// Identity of the defeater set applied by this lowering.
pub const DEFEATER_SET: &str = "org.gooi.lowering.prisma_schema/defeaters@1";

pub const LOWERING_ID: &str = "org.gooi.lowering.prisma_schema@1";

/// Fallback name for an enumeration whose name the waist did not carry.
pub const ENUM_FALLBACK: &str = "GooiEnumeration";

/// Something the waist could not supply, which the target requires.
fn prisma_type(ty: FieldType) -> Option<&'static str> {
    Some(match ty {
        FieldType::Scalar(s) => match s {
            ScalarType::Text => "String",
            ScalarType::Integer => "Int",
            ScalarType::BigInteger => "BigInt",
            ScalarType::Float => "Float",
            ScalarType::Decimal => "Decimal",
            ScalarType::Boolean => "Boolean",
            ScalarType::Timestamp => "DateTime",
            ScalarType::Date => "DateTime",
            ScalarType::Time => "DateTime",
            ScalarType::Json => "Json",
            ScalarType::Bytes => "Bytes",
            ScalarType::Uuid => "String",
            ScalarType::Enumeration => ENUM_FALLBACK,
            ScalarType::Other => "String",
        },
        FieldType::Unknown => return None,
    })
}

/// Prisma identifiers must start with a letter. Names that do not are emitted
/// under a legal identifier plus an explicit mapping back to the real name.
fn legal_identifier(name: &str) -> Option<String> {
    let cleaned: String = name
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect();
    let trimmed = cleaned.trim_start_matches('_').to_owned();
    if trimmed.is_empty() || !trimmed.starts_with(|c: char| c.is_ascii_alphabetic()) {
        return None;
    }
    if trimmed == name { None } else { Some(trimmed) }
}

struct Naming {
    /// entity name as it appears in the waist -> model identifier used in output
    model: BTreeMap<String, String>,
}

impl Naming {
    fn build(model: &DataModel) -> Self {
        let mut map = BTreeMap::new();
        for e in &model.entities {
            let ident = legal_identifier(&e.name).unwrap_or_else(|| e.name.clone());
            map.insert(e.name.clone(), ident);
        }
        Self { model: map }
    }
    fn ident(&self, entity: &str) -> String {
        self.model
            .get(entity)
            .cloned()
            .unwrap_or_else(|| entity.to_owned())
    }
}

/// A back-reference field name for the inverse side of a relation, which the
/// waist does not carry.
fn back_reference(target_of: &str, index: usize) -> String {
    let base: String = target_of
        .chars()
        .filter(|c| c.is_ascii_alphanumeric())
        .collect();
    let mut name = base;
    if let Some(first) = name.get(0..1) {
        name = format!("{}{}", first.to_lowercase(), &name[1..]);
    }
    if index == 0 {
        format!("{name}Ref")
    } else {
        format!("{name}Ref{index}")
    }
}

pub fn lower_to_prisma(model: &DataModel) -> Defeasible<String> {
    let mut out = Defeasible::new(<String>::default(), DEFEATER_SET);
    let naming = Naming::build(model);
    let mut s = String::new();

    writeln!(s, "// generated by {LOWERING_ID}").expect("string write");
    writeln!(s, "datasource db {{").expect("string write");
    writeln!(s, "  provider = \"postgresql\"").expect("string write");
    writeln!(s, "  url      = env(\"DATABASE_URL\")").expect("string write");
    writeln!(s, "}}\n").expect("string write");

    // One declaration per distinct enumeration, shared by every field using it.
    let mut seen_enums: BTreeMap<String, Vec<String>> = BTreeMap::new();
    for f in model.entities.iter().flat_map(|e| &e.fields) {
        if f.ty != FieldType::Scalar(ScalarType::Enumeration) {
            continue;
        }
        match &f.enumeration {
            Some(e) if !e.members.is_empty() => {
                seen_enums.insert(e.name.clone(), e.members.clone());
            }
            _ => {
                out.defeat(Defeat::new(
                    DefeatKind::LookedAndBlocked,
                    "enumeration".to_owned(),
                    "an enumeration arrived without members; a placeholder is emitted".to_owned(),
                ));
                seen_enums
                    .entry(ENUM_FALLBACK.to_owned())
                    .or_insert_with(|| vec!["PLACEHOLDER".to_owned()]);
            }
        }
    }
    for (name, members) in &seen_enums {
        writeln!(s, "enum {name} {{").expect("string write");
        for m in members {
            writeln!(s, "  {m}").expect("string write");
        }
        writeln!(s, "}}\n").expect("string write");
    }

    // Inverse sides, grouped by the entity that must host them.
    let mut inverses: BTreeMap<String, Vec<(String, bool)>> = BTreeMap::new();
    for (i, rel) in model.relations.iter().enumerate() {
        let Some(from) = model.entity(&rel.from_entity) else {
            out.defeat(Defeat::new(
                DefeatKind::SubjectUnresolvable,
                format!("{} -> {}", rel.from_entity, rel.to_entity),
                "relation source entity is absent from the model".to_owned(),
            ));
            continue;
        };
        // Cardinality is read off the waist: a unique foreign key is one-to-one.
        let singular = rel
            .from_fields
            .iter()
            .all(|c| from.field(c).map(|f| f.unique.is_yes()).unwrap_or(false));
        inverses
            .entry(rel.to_entity.clone())
            .or_default()
            .push((back_reference(&rel.from_entity, i), singular));
    }

    for entity in &model.entities {
        let ident = naming.ident(&entity.name);
        writeln!(s, "model {ident} {{").expect("string write");

        let identity: Vec<&FieldShape> = entity
            .fields
            .iter()
            .filter(|f| f.identity.is_yes())
            .collect();
        let compound_id = identity.len() > 1;

        for field in &entity.fields {
            emit_field(&mut s, entity, field, compound_id, &mut out);
        }

        // relation fields owned by this entity
        for (i, rel) in model.relations.iter().enumerate() {
            if rel.from_entity != entity.name {
                continue;
            }
            let target = naming.ident(&rel.to_entity);
            let refs = if rel.to_fields.is_empty() {
                model
                    .entity(&rel.to_entity)
                    .map(|t| {
                        t.fields
                            .iter()
                            .filter(|f| f.identity.is_yes())
                            .map(|f| f.name.clone())
                            .collect::<Vec<_>>()
                    })
                    .unwrap_or_default()
            } else {
                rel.to_fields.clone()
            };
            if refs.is_empty() {
                out.defeat(Defeat::new(
                    DefeatKind::SubjectUnresolvable,
                    format!("{} -> {}", rel.from_entity, rel.to_entity),
                    "no referenced fields and no identity on the target".to_owned(),
                ));
                continue;
            }
            let name = format!("{}Rel{i}", lower_first(&target));
            writeln!(
                s,
                "  {name} {target} @relation(fields: [{}], references: [{}])",
                rel.from_fields.join(", "),
                refs.join(", ")
            )
            .expect("string write");
        }

        // inverse sides hosted here
        if let Some(list) = inverses.get(&entity.name) {
            for (name, singular) in list {
                let source = model
                    .relations
                    .iter()
                    .find(|r| r.to_entity == entity.name)
                    .map(|r| naming.ident(&r.from_entity))
                    .unwrap_or_default();
                let _ = &source;
                writeln!(
                    s,
                    "  {name} {}",
                    inverse_type(model, &naming, entity, name, *singular)
                )
                .expect("string write");
            }
        }

        if compound_id {
            let cols: Vec<String> = identity.iter().map(|f| f.name.clone()).collect();
            writeln!(s, "  @@id([{}])", cols.join(", ")).expect("string write");
        }
        for set in &entity.unique_sets {
            writeln!(s, "  @@unique([{}])", set.join(", ")).expect("string write");
        }
        if ident != entity.name {
            writeln!(s, "  @@map(\"{}\")", entity.name).expect("string write");
        }
        writeln!(s, "}}\n").expect("string write");
    }

    out.value = s;
    out
}

fn inverse_type(
    model: &DataModel,
    naming: &Naming,
    host: &EntityShape,
    back_ref_name: &str,
    singular: bool,
) -> String {
    // Find which relation produced this back reference, by matching the name.
    for (i, rel) in model.relations.iter().enumerate() {
        if rel.to_entity != host.name {
            continue;
        }
        if back_reference(&rel.from_entity, i) != back_ref_name {
            continue;
        }
        let t = naming.ident(&rel.from_entity);
        return if singular {
            format!("{t}?")
        } else {
            format!("{t}[]")
        };
    }
    "Unsupported(\"unresolved\")".to_owned()
}

fn lower_first(s: &str) -> String {
    match s.get(0..1) {
        Some(f) => format!("{}{}", f.to_lowercase(), &s[1..]),
        None => s.to_owned(),
    }
}

fn emit_field(
    s: &mut String,
    entity: &EntityShape,
    field: &FieldShape,
    compound_id: bool,
    out: &mut Defeasible<String>,
) {
    let enum_name = field
        .enumeration
        .as_ref()
        .filter(|e| !e.members.is_empty())
        .map(|e| e.name.clone());
    let Some(base) = enum_name.as_deref().or_else(|| prisma_type(field.ty)) else {
        out.defeat(Defeat::new(
            DefeatKind::LookedAndBlocked,
            format!("{}.{}", entity.name, field.name),
            "field type is unknown and has no target representation".to_owned(),
        ));
        return;
    };
    let ident = legal_identifier(&field.name);
    let emitted = ident.clone().unwrap_or_else(|| field.name.clone());

    let mut ty = base.to_owned();
    if field.list {
        ty.push_str("[]");
    } else if field.nullable == Presence::Optional {
        ty.push('?');
    }

    let mut attrs: Vec<String> = Vec::new();
    if field.identity.is_yes() && !compound_id {
        attrs.push("@id".to_owned());
    }
    if field.unique.is_yes() {
        attrs.push("@unique".to_owned());
    }
    match field.default {
        DefaultOrigin::None => {}
        DefaultOrigin::Application => attrs.push("@default(cuid())".to_owned()),
        DefaultOrigin::Database => {
            out.defeat(Defeat::new(
                DefeatKind::LookedAndBlocked,
                format!("{}.{}", entity.name, field.name),
                "a store-side default exists but the waist does not carry its expression"
                    .to_owned(),
            ));
            attrs.push("@default(dbgenerated(\"__unspecified__\"))".to_owned());
        }
        DefaultOrigin::Unknown => {
            out.defeat(Defeat::new(
                DefeatKind::LookedAndBlocked,
                format!("{}.{}", entity.name, field.name),
                "the source authority could not see whether a default exists".to_owned(),
            ));
        }
    }
    if field.ty == FieldType::Scalar(ScalarType::Uuid) {
        attrs.push("@db.Uuid".to_owned());
    }
    if let Some(_renamed) = &ident {
        attrs.push(format!("@map(\"{}\")", field.name));
    }

    let joined = if attrs.is_empty() {
        String::new()
    } else {
        format!(" {}", attrs.join(" "))
    };
    writeln!(s, "  {emitted} {ty}{joined}").expect("string write");
}

#[cfg(test)]
mod tests {
    use super::*;
    use semantics_data_model_v1::{EntityShape, FieldShape};

    fn field(name: &str, ty: ScalarType) -> FieldShape {
        FieldShape {
            name: name.to_owned(),
            ty: FieldType::Scalar(ty),
            nullable: Presence::Required,
            list: false,
            identity: semantics_data_model_v1::Tri::No,
            unique: semantics_data_model_v1::Tri::No,
            default: DefaultOrigin::None,
            default_value: None,
            enumeration: None,
        }
    }

    #[test]
    fn emits_a_parseable_model_with_identity() {
        let mut id = field("id", ScalarType::Text);
        id.identity = semantics_data_model_v1::Tri::Yes;
        let m = DataModel {
            entities: vec![EntityShape {
                name: "User".to_owned(),
                fields: vec![id, field("email", ScalarType::Text)],
                unique_sets: Vec::new(),
            }],
            relations: Vec::new(),
        };
        let out = lower_to_prisma(&m);
        assert!(out.value.contains("model User {"));
        assert!(out.value.contains("id String @id"));
        assert!(out.is_exhaustive());
    }

    #[test]
    fn an_illegal_identifier_is_mapped_not_mangled_silently() {
        let m = DataModel {
            entities: vec![EntityShape {
                name: "_JoinTable".to_owned(),
                fields: vec![field("A", ScalarType::Text)],
                unique_sets: Vec::new(),
            }],
            relations: Vec::new(),
        };
        let out = lower_to_prisma(&m);
        assert!(out.value.contains("model JoinTable {"));
        assert!(out.value.contains("@@map(\"_JoinTable\")"));
    }

    #[test]
    fn a_store_side_default_is_reported_as_lossy() {
        let mut f = field("created", ScalarType::Timestamp);
        f.default = DefaultOrigin::Database;
        let m = DataModel {
            entities: vec![EntityShape {
                name: "A".to_owned(),
                fields: vec![f],
                unique_sets: Vec::new(),
            }],
            relations: Vec::new(),
        };
        let out = lower_to_prisma(&m);
        assert!(out.defeats.iter().any(|d| d.reason.contains("expression")));
    }
}
